// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Demo = require("../src/Demo.bs.js");
var Tests = require("./Tests.bs.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

var equals = Caml_obj.caml_equal;

var notEquals = Caml_obj.caml_notequal;

function randomTests(loc) {
  [
      1,
      5,
      6,
      9
    ].forEach(function (num) {
        return Tests.run(loc, Demo.add(num, num), equals, (num << 1));
      });
  
}

function init(param) {
  Tests.run([
        [
          "ATest.re",
          20,
          15,
          45
        ],
        "Adding 2 numbers should work"
      ], Demo.add(1, 2), equals, 3);
  randomTests([
        [
          "ATest.re",
          25,
          25,
          64
        ],
        "Adding random numbers should work too"
      ]);
  return Tests.run([
              [
                "ATest.re",
                29,
                15,
                26
              ],
              "1 + 3 = 2"
            ], Demo.add(1, 3), equals, 2);
}

exports.equals = equals;
exports.notEquals = notEquals;
exports.randomTests = randomTests;
exports.init = init;
/* Tests Not a pure module */
