// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Demo = require("../src/Demo.bs.js");
var Tests = require("./Tests.bs.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

var equals = Caml_obj.caml_equal;

function randomTests(loc) {
  [
      1,
      5,
      6,
      9
    ].forEach(function (num) {
        return Tests.run(loc, Demo.add(num, num), equals, (num << 1));
      });
  
}

function run(param) {
  Tests.run([
        [
          "DemoTest.res",
          17,
          15,
          45
        ],
        "Adding 2 numbers should work"
      ], Demo.add(1, 2), equals, 3);
  return randomTests([
              [
                "DemoTest.res",
                22,
                25,
                64
              ],
              "Adding random numbers should work too"
            ]);
}

exports.equals = equals;
exports.randomTests = randomTests;
exports.run = run;
/* Tests Not a pure module */
