// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Demo = require("../src/Demo.bs.js");
var Tests = require("./Tests.bs.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

var equals = Caml_obj.caml_equal;

Tests.run([
      [
        "Demo2Test.re",
        7,
        13,
        24
      ],
      "1 + 3 = 2"
    ], Demo.add(1, 3), equals, 2);

exports.equals = equals;
/*  Not a pure module */
