// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var DemoTest = require("./DemoTest.bs.js");
var RandomTest = require("./RandomTest.bs.js");

DemoTest.run(undefined);

RandomTest.run(undefined);

/*  Not a pure module */
