// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var DemoTest = require("./DemoTest.bs.js");
var Demo2Test = require("./Demo2Test.bs.js");

DemoTest.run(undefined);

Demo2Test.run(undefined);

/*  Not a pure module */
