// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Path = require("path");
var Curry = require("bs-platform/lib/js/curry.js");
var CodeFrame = require("@babel/code-frame");

var dirname = typeof __dirname === "undefined" ? undefined : __dirname;

var dirname$1 = dirname !== undefined ? dirname : "";

function run(loc, left, comparator, right) {
  if (Curry._2(comparator, left, right)) {
    return ;
  }
  var match = loc[0];
  var file = match[0];
  var fileContent = Fs.readFileSync(Path.join(dirname$1, file), {
        encoding: "utf-8"
      });
  console.error("\u001b[31mTest Failure:\u001b[39m " + file);
  console.error(CodeFrame.codeFrameColumns(fileContent, {
            start: {
              line: match[1]
            }
          }, {
            highlightCode: true
          }));
  console.error("\u001b[31mLeft:\u001b[39m");
  console.error(left);
  console.error("\u001b[31mRight:\u001b[39m");
  console.error(right);
  process.exit(1);
  
}

exports.dirname = dirname$1;
exports.run = run;
/* dirname Not a pure module */
