// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function not(x) {
  if (x) {
    return /* True */0;
  } else {
    return /* False */1;
  }
}

function equive(x, y) {
  if (x) {
    if (y) {
      return /* True */0;
    } else {
      return /* False */1;
    }
  } else if (y) {
    return /* False */1;
  } else {
    return /* True */0;
  }
}

function or(x, y) {
  if (x && y) {
    return /* False */1;
  } else {
    return /* True */0;
  }
}

function boolean_to_str(x) {
  if (x) {
    return "false";
  } else {
    return "true";
  }
}

var res = or(/* True */0, /* False */1);

console.log(res, res ? "false" : "true");

exports.not = not;
exports.equive = equive;
exports.or = or;
exports.boolean_to_str = boolean_to_str;
exports.res = res;
/* res Not a pure module */
