// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var ReactDom = require("react-dom");

var $$Document = {};

function Counter$Counter(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  var count = match[0];
  React.useEffect(function () {
        document.title = "You clicked " + String(count) + " times!";
        
      });
  var onClick = function (_evt) {
    return Curry._1(setCount, (function (prev) {
                  return prev + 1 | 0;
                }));
  };
  var msg = "You clicked " + String(count) + " times";
  return React.createElement("div", undefined, React.createElement("p", undefined, msg), React.createElement("button", {
                  onClick: onClick
                }, "Click me"));
}

var Counter = {
  make: Counter$Counter
};

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(Counter$Counter, {}), root);
}

exports.$$Document = $$Document;
exports.Counter = Counter;
/* root Not a pure module */
