// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function add(x, y) {
  return x + y | 0;
}

function add$p(x, y) {
  return x + y | 0;
}

var b = add$p(1, 2);

var a = 3;

exports.add = add;
exports.add$p = add$p;
exports.a = a;
exports.b = b;
/* b Not a pure module */
