// Generated by ReScript, PLEASE EDIT WITH CARE


console.log("Hello, World!");

console.log([
        1,
        2,
        3
      ].map(function (x) {
          return x + 1 | 0;
        }));

export {
  
}
/*  Not a pure module */
