// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_js_exceptions = require("rescript/lib/js/caml_js_exceptions.js");

function fn(x) {
  if (x > 0) {
    return x;
  }
  throw {
        RE_EXN_ID: "Not_found",
        Error: new Error()
      };
}

var res;

try {
  res = fn(-1);
}
catch (raw_exn){
  var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
  if (exn.RE_EXN_ID === "Not_found") {
    res = 0;
  } else {
    throw exn;
  }
}

console.log("res is" + res.toString());

exports.fn = fn;
exports.res = res;
/* res Not a pure module */
