// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Belt_List = require("rescript/lib/js/belt_List.js");

function even(x) {
  return x % 2 === 0;
}

function odd(x) {
  return x % 2 === 1;
}

function filter(fn, _lst) {
  while(true) {
    var lst = _lst;
    if (!lst) {
      return /* [] */0;
    }
    var tail = lst.tl;
    var head = lst.hd;
    if (Curry._1(fn, head)) {
      return Belt_List.add(filter(fn, tail), head);
    }
    _lst = tail;
    continue ;
  };
}

function filter_aux(fn, _acc, _lst) {
  while(true) {
    var lst = _lst;
    var acc = _acc;
    if (!lst) {
      return Belt_List.reverse(acc);
    }
    var head = lst.hd;
    _lst = lst.tl;
    _acc = Curry._1(fn, head) ? Belt_List.add(acc, head) : acc;
    continue ;
  };
}

function filter_tr(fn, lst) {
  return filter_aux(fn, /* [] */0, lst);
}

var lst = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: {
        hd: 4,
        tl: /* [] */0
      }
    }
  }
};

var filtered = filter_aux(even, /* [] */0, lst);

console.log(Belt_List.toArray(filtered));

exports.even = even;
exports.odd = odd;
exports.filter = filter;
exports.filter_aux = filter_aux;
exports.filter_tr = filter_tr;
exports.lst = lst;
exports.filtered = filtered;
/* filtered Not a pure module */
