// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var A = {
  x: 0
};

function IncX(M) {
  var x = M.x + 1 | 0;
  return {
          x: x
        };
}

function AddX(M) {
  var add = function (y) {
    return M.x + y | 0;
  };
  return {
          add: add
        };
}

var x = 1;

var B = {
  x: x
};

var x$1 = x + 1 | 0;

var C = {
  x: x$1
};

function add(y) {
  return 0 + y | 0;
}

var Add42 = {
  add: add
};

exports.A = A;
exports.IncX = IncX;
exports.AddX = AddX;
exports.B = B;
exports.C = C;
exports.Add42 = Add42;
/* No side effect */
