// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function MyComp(Props) {
  var name = Props.name;
  var color = Props.color;
  var colorStr = color ? "blue" : "red";
  return React.createElement("div", {
              className: "color-" + colorStr
            }, name);
}

var make = MyComp;

exports.make = make;
/* react Not a pure module */
