// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function plus(x, y) {
  if (x) {
    return /* Succ */{
            _0: plus(x._0, y)
          };
  } else {
    return y;
  }
}

function mult(x, y) {
  if (x) {
    return plus(y, mult(x._0, y));
  } else {
    return /* Z */0;
  }
}

function int_of_nat(x) {
  if (x) {
    return 1 + int_of_nat(x._0) | 0;
  } else {
    return 0;
  }
}

var one = /* Succ */{
  _0: /* Z */0
};

var two = plus(one, one);

var four = mult(two, two);

console.log("two is", two, int_of_nat(two));

console.log("four is", four, int_of_nat(four));

exports.plus = plus;
exports.mult = mult;
exports.int_of_nat = int_of_nat;
exports.one = one;
exports.two = two;
exports.four = four;
/* two Not a pure module */
