// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function greeting(person) {
  if (typeof person === "number") {
    if (person !== 0) {
      return "Hello Director.";
    } else {
      return "Hey Professor!";
    }
  }
  var anyOtherName = person._0;
  if (anyOtherName === "Richard") {
    return "Still here Ricky?";
  } else {
    return "Hey, " + (anyOtherName + ".");
  }
}

exports.greeting = greeting;
/* No side effect */
