// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function plus(x, y) {
  return x + y | 0;
}

function mul(x, y) {
  return Math.imul(x, y);
}

function neg(x) {
  return -x | 0;
}

function to_string(prim) {
  return String(prim);
}

var IntRing = {
  zero: 0,
  one: 1,
  plus: plus,
  mul: mul,
  neg: neg,
  to_string: to_string
};

function plus$1(x, y) {
  return x + y;
}

function mul$1(x, y) {
  return x * y;
}

function neg$1(x) {
  return -x;
}

function to_string$1(prim) {
  return prim.toString();
}

var FloatRing = {
  zero: 0,
  one: 1,
  plus: plus$1,
  mul: mul$1,
  neg: neg$1,
  to_string: to_string$1
};

function plus$2(x, y) {
  return x + y;
}

function mul$2(x, y) {
  return x * y;
}

function neg$2(x) {
  return -x;
}

function to_string$2(prim) {
  return prim.toString();
}

var FloatRing2 = {
  zero: 0,
  one: 1,
  plus: plus$2,
  mul: mul$2,
  neg: neg$2,
  to_string: to_string$2
};

var B = {};

var A = {};

var C = {
  A: A
};

var Ax = IntRing;

var Bx = FloatRing;

exports.IntRing = IntRing;
exports.FloatRing = FloatRing;
exports.Ax = Ax;
exports.Bx = Bx;
exports.FloatRing2 = FloatRing2;
exports.B = B;
exports.C = C;
/* No side effect */
