// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDom = require("react-dom");

function Test$Hello(Props) {
  return React.createElement("div", undefined, "Hello World");
}

var Hello = {
  make: Test$Hello
};

function Test$World(Props) {
  var name = Props.name;
  var greeting = name !== undefined ? "Hello " + name + "!" : "Hello stranger!";
  return React.createElement("div", undefined, greeting);
}

var World = {
  make: Test$World
};

var name = "Leonty";

var root = document.querySelector("#root");

if (!(root == null)) {
  var tmp = {};
  if (name !== undefined) {
    tmp.name = name;
  }
  ReactDom.render(React.createElement("div", undefined, React.createElement(Test$World, tmp), React.createElement(Test$Hello, {})), root);
}

exports.Hello = Hello;
exports.World = World;
exports.name = name;
/* root Not a pure module */
