// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");

var one = /* Next */{
  _0: /* Zero */0
};

var two = /* Next */{
  _0: one
};

var three = /* Next */{
  _0: two
};

var four = /* Next */{
  _0: three
};

function sum(_a, _b) {
  while(true) {
    var b = _b;
    var a = _a;
    if (!a) {
      return b;
    }
    _b = /* Next */{
      _0: b
    };
    _a = a._0;
    continue ;
  };
}

console.log(Caml_obj.caml_equal(sum(two, two), four));

exports.one = one;
exports.two = two;
exports.three = three;
exports.four = four;
exports.sum = sum;
/*  Not a pure module */
